- name: debug
  debug:
    msg: "Jeste cloudflare"

- name: include tasks for zone
  include_tasks: loop_zone.yml
  loop: "{{ app.value.dns.configs.zones|default({})|dict2items }}"
  loop_control:
    loop_var: _zone
